apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: decco-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: decco-operator
    spec:
      serviceAccountName: decco-operator
      containers:
      - name: decco-operator
        image: platform9/decco-operator
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DNS_PROVIDER_NAME
          value: aws-route53
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: decco-operator-secret
              key: awsAccessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: decco-operator-secret
              key: awsSecretAccessKey
        - name: SLACK_WEBHOOK_FOR_DNS_UPDATE_FAILURE
          valueFrom:
            secretKeyRef:
              name: decco-operator-secret
              key: slackWebhookForDnsUpdateFailure
