apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: k8sniff
  name: k8sniff-default
  namespace: decco
spec:
  backend:
    serviceName: nginx-ingress
    servicePort: 443